### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by balupton** [bevry/kava#7]
I think the poor adoption with joe is largely due to it's terrible name. I'm open to suggestions.

**Comment by balupton** [comment]
What do people think of `fairtrade`? Anyone have any objections. I like it, as it stays within the chocolate/coffee/tea namespace, while providing more guarantees.

**Comment by pflannery** [comment]
@balupton I think fair trade isn't a bad name but I've always looked at fair trade relating to fairness across trade in general. 

Its got me thinking how a person would test or choose their coffee or tea.

Some words I've put together are taste, aroma\smell, roast(ed), hot, blends, fresh, ripe, colour, drinking, cuppa joe, or cup\mug.

A project I worked on recently I named the ci build user "cijoe" as a bit of humour.
Maybe joe just needs a little something to go with it.

**Comment by pflannery** [comment]
or maybe it just need a logo like:

![image](https://cloud.githubusercontent.com/assets/1727302/9976826/c4f3ef8e-5ee7-11e5-8363-fdaed3ea36b1.png)

:)

**Comment by timhuff** [comment]
I figured I'd drop my two cents here. I'm probably not going to use `joe`. Here's my current situation: I'm using mocha and want to generate tests using information pulled from my database. It seems your library suits my use case. I'm not yet positive if I'll use this tool but I'm hesitant for several reasons. For one, this is not a drop in replacement for `mocha` and I already have a decent number of tests written. Secondly, this is not an extension of mocha but rather a replacement for it. I'm hesitant to risk committing to such a fundamental tool in the hopes that it continues to be maintained (meanwhile `mocha`'s not going anywhere soon). There's also the question of "does this play nicely with my other testing tools?". It'd be excellent if this tool simply modified mocha to not run until a callback, provided by `describe` is called. Solves my problem and is only a minor departure from my existing testing ecosystem.

**Comment by balupton** [comment]
Mocha is not well designed, patching it is not possible. This tool will be maintained.

**Comment by balupton** [comment]
> Maybe joe just needs a little something to go with it.

Yeah maybe. Although I'd still hate to have the name `Joe` at a company that uses `joe` :P

---

I've reserved the name `fairtrade` by cross-publishing joe to it. Will make the name change later on.

**Comment by balupton** [comment]
`fairtest` is also an option

**Comment by balupton** [comment]
`kava` is also an option, if I email the people behind the unused packages

**Comment by balupton** [comment]
Replaced

> Joe is a javascript testing framework that actually works. Unlike Mocha, we won't die on you abruptly when executing dynamically created tests and are always able to associate the correct test to the correct corresponding test suite.  Switching from Mocha is trivial and only takes a few minutes.

With

> Joe is an accurate and powerful testing framework that can run on node and in the browser

In v2.0.1

**Comment by rdeforest** [comment]
New potential user here, providing my perspective. I was going to write a huge wall of text, but instead I'm putting it on your wiki (as ["Notes on a possible project re-branding"](https://github.com/bevry/joe/wiki/Notes-on-a-possible-project-re-branding)) so folks can hack at it instead of producing a long series of posts on this issue. Discussion should still happen here, but the results of the discussion should go on the wiki.

**Comment by balupton** [comment]
I've sent the following email to @samholmes to request the `kava` name.

```
Hi Sam,

With your blessing, I'd like rename https://github.com/bevry/joe to kava — https://github.com/bevry/joe/issues/7 — and as such, publish to the npm package name `kava` which is currently under your control with an empty package https://www.npmjs.com/package/kava

Joe has been powering the tests of the Bevry ecosystem since 2012, and will continue doing so for the foreseeable future.

As per the process at https://docs.npmjs.com/misc/disputes you can approve this move by running:

npm owner add bevryme kava
npm owner add balupton kava
npm owner rm samholmes kava

Thank you for your consideration. I will happily mention your blessing if you wish in the changelog once the rename has completed.

Regards,
Benjamin Lupton
https://balupton.com
```

**Comment by balupton** [comment]
In the meantime, I will publish to `@bevry/kava`

**Comment by balupton** [comment]
@samholmes has graciously given us the package name `kava`.

A new release will go up in the coming week in the next batch of dev work.

**Comment by balupton** [comment]
Kava v3 has been released.
