### ISSUE TITLE
Feature Request: global or suite-wide test timeouts

### ISSUE THREAD

**Issue by christav** [bevry/kava#9]
It would be quite useful, especially when dealing with integration testing, if there was an easy way to say "every test should complete within X seconds", either on a global or per-suite basis. If the timeout expires before the completion callback is called, the test fails.

You can do this right now with an explicit setTimeout inside each test, but that needs to be repeated in each test.

**Comment by balupton** [comment]
@christav do you still find yourself using this, as I'm probably going to remove this in the upcoming taskgroup release - and perhaps add it directly to joe rather than the current implementation inside taskgroup
